name: rewards
on:
  workflow_dispatch:
  schedule:
    # CRON Generator Link: https://crontab.guru/#5_1_*_*_*
    # Below is 01:05 AM UTC
    - cron: "5 1 * * *"
jobs:
  login-account:
    runs-on: ubuntu-latest
    environment: GS4
    name: login account
    timeout-minutes: 5
    steps:
      - uses: ondreian/simu-rewards@v1.1.0
        with:
          account: ${{ secrets.ACCOUNT1 }}
          password: ${{ secrets.PASSWORD1 }}
          game: ${{ secrets.GAME1 }}
